### PR TITLE
Add kw to drop warmup samples

### PR DESCRIPTION
**Pull request by xukai92**

### CODE REVIEW

**Comment by yebai** [comment]
Looks good to me. 

@cpfiffer Will this affect the Gibbs sampler, as you mentioned in #35 ?

**Comment by xukai92** [comment]
Also I notice TemperedLeapfrog with adaptation is more likely to fail the tests. Do you think tempering should actually be disabled during adaptation phase?

**Comment by yebai** [comment]
> Also I notice TemperedLeapfrog with adaptation is more likely to fail the tests. Do you think tempering should actually be disabled during adaptation phase?


Which sampler are you using?

**Comment by xukai92** [comment]
Static HMC; see https://travis-ci.org/TuringLang/AdvancedHMC.jl/jobs/592055365#L377.

I already disable HMCDA with TemperedLeapfrog (https://github.com/TuringLang/AdvancedHMC.jl/blob/master/test/hmc.jl#L41) as this combination seems to be extremly unstable.

**Comment by yebai** [comment]
It is likely tempering won't play nicely with NUTS yet, due to multiple calls to `step` in each dynamic trajectory.

**Comment by yebai** [comment]
Happy to disable tempering during adaption for all cases.

**Pull request merged**
