### PR TITLE
Unifying trajectories

### PR DESCRIPTION
**Pull request by xukai92**
This PR solves #13 and #103 together by explicitly separating `Trajectory` from `HMCKernel`,
without introducing any functionality change.
I also take this chance to unify the notation as discussed in #48,
in which I use `τ` to refer a (numerical) Hamiltonian trajectory and `κ` to refer a MCMC kernel.

As a showcase, below is how to construct NUTS now:

```julia
τ = Trajectory(Leapfrog(1e-3), NoUTurn())
κ = HMCKernel(FullRefreshment(), τ, MultinomialTS)
```

As suggested by https://github.com/TuringLang/AdvancedHMC.jl/issues/103#issue-496507285,
fixed simulation steps or length are unified as termination criteria.
A nice benefit of this is that the parameters regarding trajectory simulation are clear:
e.g. `FixedNSteps(10)`, `NoUTurn(5, 1_000)` or `NoUTurn(max_depth=5)`.

This design mimics the conceptual procedure of doing HMC:

1. Refresh momentum
2. Simulate trajectory
3. Propose a point from the simulated trajectory

although usually the procedure of 2 and 3 are quite coupled.

As a result, the main `transition` function looks like this.
```julia
function transition(rng, h, κ::HMCKernel, z)
    @unpack refreshment, τ, TS = κ
    τ = reconstruct(τ, integrator=jitter(rng, τ.integrator))
    z = refresh(rng, z, h, refreshment)
    return transition(rng, h, τ, TS, z)
end
```
As a side product of solving #13,
it also unifies how integrators are jittered - all before simulating the trajectory in the same place where momentum variables are refreshed.
With this design, this is the only place where `jitter` and `refresh` is called.

### CODE REVIEW

**Comment by xukai92** [comment]
Besides, 
I separated `trajectory.jl` into `kernel.jl` + `trajectory_static.jl` & `trajectory_dynamic.jl`.
In hope to make the review process easier, I reverted this, but it doesn't seem that the changes is well captured by Git.

**Comment by xukai92** [comment]
I hope we can have https://github.com/TuringLang/AdvancedHMC.jl/pull/208 merged first so that this PR can be Geweke tested,
which would give us some confidence that the refactoring didn't break anything.

**Comment by xukai92** [comment]
As a validation of this refactoring doesn't change any functionality,
I run `test/demo.jl` for this branch (62bfed7) and the master, and compare the simulated chains and the statistics,
which are exactly the same.

**Comment by xukai92** [comment]
I added regression tests to compare the exact simulated chains and statistics in daade0a1a01f834d68b5af705d0bf9a4bee4f0ba for the four variants.

- Static HMC with MH
- Static HMC with multinomial
- NUTS with slice
- NUTS with multinomial

These should be a good enough indicator that the functionality doesn't got changed.

**Comment by xukai92** [comment]
I disabled the regression test on CI because the results from master is platform & Julia version dependent.
The file generated is from my local (macOS) with Julia 1.5-rc2;
I will make sure all my commits pass the test locally.
If we were to support it on CI we need to generate chains and statistics for all variants, platforms and Julia version.
I would consider it as a future work.

**Comment by xukai92** [comment]
Just a few notes:

- I believe this option is more modular in terms of constructing HMC algorithms on a single target. It can be seen how it results into a clean construction for users and a clean multiple dispatch in our code base.
- @yebai If you agree with this design, I'm happy to break this PR into a few small ones to make the review eaiser.

**Comment by yebai** [comment]
Yes, it can be helpful to break this PR into two smaller ones: one focusing on unifying trajectory types, another focusing on momentum refreshment.

**Comment by xukai92** [comment]
Yes. Let me close this one first and create one for unifying trajectory types first, which is less controversial.

**Pull request closed without merging**
